#Minecraft server properties
#Wed Apr 29 21:37:24 BRT 2026
generator-settings=
allow-nether=false
level-name=world
enable-query=false
allow-flight=false
rcon.password=mgpvp2026x
server-port=25565
level-type=FLAT
enable-rcon=true
force-gamemode=false
level-seed=
server-ip=
max-build-height=256
spawn-npcs=true
allow-end=false
white-list=false
debug=false
spawn-animals=true
texture-pack=
snooper-enabled=false
hardcore=false
online-mode=false
pvp=true
difficulty=2
server-name=MagicPVP
enable-command-block=true
gamemode=0
max-players=100
rcon.port=25575
spawn-monsters=true
view-distance=5
generate-structures=false
spawn-protection=0
motd=\u00C2\u00A78[\u00C2\u00A7aMagicPVP\u00C2\u00A78] \u00C2\u00A7fFullPvP Raiz 1.5.2
