#Minecraft server properties
#Sun Sep 14 10:20:09 PDT 2025
generator-settings=
allow-nether=false
level-name=world
enable-query=false
allow-flight=false
server-port=25565
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=192.168.1.56
max-build-height=500
spawn-npcs=true
allow-end=false
white-list=false
spawn-animals=true
texture-pack=
snooper-enabled=true
hardcore=false
online-mode=false
pvp=true
difficulty=1
server-name=Unknown Server
enable-command-block=true
gamemode=0
max-players=20
spawn-monsters=true
view-distance=10
generate-structures=true
spawn-protection=16
motd=MagicPVP a magia junto com a nostalgia
